### ISSUE TITLE
g functions in molden format

### ISSUE THREAD

**Issue by Jellby** [steabert/molpy#10]
Can penny write g functions in Molden format? I was using cc-pV5Z with carbon atoms, which includes up to h functions, Molcas didn't write a .molden file because Molden does not support functions higher than g. OK, I thought, let's see what happens if I convert it with penny... and what happens is that it creates a .molden file alright, but only with up to f functions, although g functions should be supported:

http://www.cmbi.ru.nl/molden/molden_format.html

**Comment by steabert** [comment]
Indeed, I based the initial version of the molden converter on what was in Molcas. I will increase the maximum angular momentum from f to g.
