### ISSUE TITLE
SyntaxError in penny

### ISSUE THREAD

**Issue by Jellby** [steabert/molpy#12]
With the latest version I get:

```
  File "./penny", line 360

      ^
SyntaxError: only named arguments may follow *expression
```

which refers to the line:

```
print(body.format(center, *coord, charge))
```

Do I need a more recent python version (I have 3.4.3) or...?

**Comment by steabert** [comment]
Did you handle a specific file? How can I reproduce it?
I tried `./penny --mulliken examples/cucl4-cas.h5` and that works, my python version is 3.5.2

**Comment by steabert** [comment]
After some googling, this indeed came in with Python 3.5: https://www.python.org/dev/peps/pep-0448/
Feel free to adjust to code to work with earlier Python version and send a pull request :)

**Comment by steabert** [comment]
It might work by just unpacking as

```
x, y, z = coord
... (center, x, y, z, charge) ...
```

**Comment by Jellby** [comment]
It fails simply running `./penny`. Unpacking `x, y, z` works, but I expect to update my systems soon, then I'll have python 3.5 and I won't mind.

**Comment by steabert** [comment]
OK, in that case I've just updated the README file to state that we require Python 3.5.
