### ISSUE TITLE
Spin densities?

### ISSUE THREAD

**Issue by Jellby** [steabert/molpy#4]
Can spin density orbitals be generated from the h5 file? Molcas generates SpdOrb files, but those have to be converted to something else for visualization.

Or, for converting *Orb files to molden, since *Orb files don't have basis set, could one combine two input files (like orbitals from *Orb, basis from h5 or molden)?

**Comment by steabert** [comment]
The rasscf.h5 file already contains the SPINDENSITY_MATRIX dataset, so it would be fairly easy to generate orbitals from that.

The second options is more complicated, and I don't know if it is worth it. I realize it might be useful (especially with old *Orb files) but the main reason I want to avoid it is that it becomes more cumbersome to guarantee file consistency.
