### ISSUE TITLE
[Molden Format]

### ISSUE THREAD

**Issue by felixplasser** [steabert/molpy#6]
Hi, another small request: jmol is only able to parse Molden format files if the header says
[Molden Format]
penny (and regular Molcas) write it all in capitals
[MOLDEN FORMAT]
which causes jmol to crash.

Is it ok, to use the first version, since this also agrees with the official Molden Format
http://www.cmbi.ru.nl/molden/molden_format.html

Thanks

**Comment by steabert** [comment]
Absolutely, thanks!
The version I wrote was based on what I could derive from the internal Molcas Fortran code. I didn't think the headers would be case sensitive (as my molden worked with these files). At the top of the specification, they do use also uppercase characters.
Anyway, I will fix it using the headers that are mentioned in each separate section.
