### ISSUE TITLE
Molden conversion with symmetry

### ISSUE THREAD

**Issue by felixplasser** [steabert/molpy#7]
Conversion to Molden does not work in the case of symmetry. The reason is that the symmetry elements are written out to the Molden file.

For example in the case of examples/h2-cas.h5:

```
[Atoms] (AU)
H1    :E         1       1      0.6614041      0.0000000      0.0000000
H1    :x         2       1     -0.6614041      0.0000000      0.0000000
```

**Comment by steabert** [comment]
Indeed, I will need to add an atom label sanitizer, I could actually do that globally.
Do you know if molden expects only element symbols, or if I can keep more interesting labels?
I guess it would know the element because of the atomic number.

**Comment by felixplasser** [comment]
I just checked, if I just delete the spaces, then the file can still be read by Molden, by Jmol, and by Openbabel. Something like this seems to be ok.

```
[Atoms] (AU)
H1:E         1       1      0.6614041      0.0000000      0.0000000
H1:x         2       1     -0.6614041      0.0000000      0.0000000
```

But the problem is that one does not know what program the user will actually choose. So it makes sense to keep things portable, I guess.
